version: '3'
services:
  game-market-app:
    container_name: game-market-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    stdin_open: true
    environment:
      NODE_ENV: production
    ports:
      - "3003:3000"
    volumes:
       - .:/app
    env_file:
      - .env