import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./header";
import { Providers } from "./providers";
import { getServerSession, } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession()
  return (
    <html lang="en" className="dark text-foreground bg-background">
      <body className={`dark text-foreground bg-background ${inter.className}`}>
        <Header  session={session}/>
        <Providers session={session}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
