import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import Header from "./header";
import AppNavbar from "./navbar";
import AppMobileNavbar from "./mobileNavbar"
import { Providers } from "./providers";
import { Session, getServerSession } from "next-auth";
import { and, eq } from "drizzle-orm";
import { db } from "@/drizzle";
import { users } from "@/drizzle/schema";
import "./globals.css";
import "primereact/resources/themes/lara-light-indigo/theme.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  console.log("session : ", session);
  try {
    if (session && (session as Session).user) {
      const sessionDbUser = await db
        .select()
        .from(users)
        .where(
          and(
            eq(users.email, (session as Session).user?.email as string),
            eq(users.username, (session as Session).user?.name as string)
          )
        );
      if (sessionDbUser.length === 0) {
        const result = await db
          .insert(users)
          .values({
            email: (session as Session).user?.email as string,
            username: (session as Session).user?.name as string,
            avatarUrl: (session as Session).user?.image as string,
            authProvider: cookies().get("authProvider")?.value as
              | "GOOGLE"
              | "FACEBOOK"
              | "GITHUB",
          })
          .returning();
      } else {
        console.log("user already exists");
      }
    }
  } catch (err) {
    console.log("error : ", err);
  }

  return (
    <html lang="en" className="dark text-foreground bg-background">
      <body className={`dark text-foreground bg-background ${inter.className}`}>
        <AppNavbar session={session}/>
        <AppMobileNavbar session={session}/>
        {/* <Header session={session} /> */}
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  );
}
